name: app
type: "java:11"
disk: 1024
hooks:
    build:  mvn clean package payara-micro:bundle
relationships:
    mongodb: 'mongodb:mongodb'
web:
    commands:
        start: java -jar $JAVA_OPTS $CREDENTIAL target/microprofile-microbundle.jar --port $PORT