# The services of the project.
#
# Each service listed will be deployed
# to power your Platform.sh project.

solr:
    type: solr:7.7
    disk: 1024
    size: S
    configuration:
        cores:
            collection1:
                conf_dir: !archive "core1-conf"
        endpoints:
            solr:
                core: collection1