version:  '3.2'

services:

  mysql:
    image: "mysql:latest"
    networks:
      - javanet
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: people
    ports:
      - 3306:3306

  rabbit:
    image: "rabbitmq:management"
    networks:
      - javanet
    ports:
      - 5672:5672
      - 15672:15672

networks:
  javanet: